# Nixkell config

ghc = "8.10.4"

[env]
tools = [
  "cabal-install",
  "cabal2nix",
  "haskell-language-server",
  "haskellPackages.implicit-hie",
  "hlint",
  "niv",
  "nixpkgs-fmt",
  "ormolu",
]

[ignore]
files = [
]
paths = [
  ".github",
  "notes",
  "tools",
]
