#!/usr/bin/env bash
set -euo pipefail

# Bundle examples/*.law and README.md into web/samples.js so the in-browser
# `:l <path>` command can read them without a network round-trip.

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$PROJECT_ROOT"

OUT="web/samples.js"
mkdir -p web

{
  echo "// Generated by scripts/generate-samples-js.sh — do not edit by hand."
  echo "export const sampleFiles = {"
  for f in examples/*.law README.md; do
    [ -f "$f" ] || continue
    key=$(printf '%s' "$f")
    value=$(node -e "process.stdout.write(JSON.stringify(require('fs').readFileSync(process.argv[1],'utf8')))" "$f")
    printf '  "%s": %s,\n' "$key" "$value"
  done
  echo "};"
} > "$OUT"

count=$(grep -c '^  "' "$OUT" || true)
echo "Wrote $OUT ($count files bundled)."
